In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_excel('./data/State_ev_data/2024.xlsx')

d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
data

,State Month Wise Data For All State (2024),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,S No,State ...,Month Wise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOTAL
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,NaN
3,1,ANDAMAN & NICOBAR ISLAND,0,0,0,1,2,3,0,3,2,2,2,5,20
4,2,ANDHRA PRADESH,126,129,399,437,540,638,724,219,202,244,692,676,"5,026"
5,3,ARUNACHAL PRADESH,5,4,2,5,1,6,12,6,7,12,13,8,81
6,4,ASSAM,20,24,64,41,42,46,69,70,68,58,76,96,674
7,5,BIHAR,59,75,112,102,90,101,112,100,78,158,142,89,"1,218"
8,6,CHANDIGARH,121,91,138,124,151,156,240,215,188,403,210,233,"2,270"
9,7,CHHATTISGARH,135,144,204,171,171,169,233,351,120,402,194,178,"2,472"
10,8,DELHI,567,503,733,800,839,"1,041","1,131",894,540,892,682,827,"9,449"
11,9,GOA,85,100,117,144,112,91,133,132,105,164,117,122,"1,422"
12,10,GUJARAT,493,510,770,758,762,627,"1,066",952,975,"1,668","1,032","1,198","10,811"
13,11,HARYANA,236,169,209,451,453,541,629,711,818,"1,007","1,095","1,078","7,397"
14,12,HIMACHAL PRADESH,15,11,18,43,51,47,63,64,60,75,99,72,618
15,13,JAMMU AND KASHMIR,13,25,34,25,24,29,33,31,41,70,42,60,427
16,14,JHARKHAND,24,32,47,52,60,61,79,76,98,104,88,71,792
17,15,KARNATAKA,847,839,"1,330","1,195","1,260","1,249","1,311","1,798","1,335","2,412","1,913","1,708","17,197"
18,16,KERALA,913,851,"1,032","1,235","1,154","1,040","1,199","1,189","1,484","1,537","1,472","1,425","14,531"
19,17,LADAKH,0,0,0,0,0,0,0,2,0,0,0,0,2
20,18,MADHYA PRADESH,204,192,226,225,221,271,314,307,235,603,364,295,"3,457"
21,19,MAHARASHTRA,"1,131","1,051","1,377","1,731","1,747","1,506","2,027","1,946","1,884","3,626","2,212","2,407","22,645"
22,20,MANIPUR,7,7,2,7,7,4,10,10,10,11,11,14,100
23,21,MEGHALAYA,1,4,3,7,9,7,7,2,8,9,9,6,72
24,22,MIZORAM,1,0,0,0,0,1,1,3,2,2,3,3,16
25,23,NAGALAND,0,1,2,2,6,0,3,5,7,8,1,0,35
26,24,ODISHA,144,201,217,202,239,167,299,237,205,420,344,367,"3,042"
27,25,PUDUCHERRY,10,14,5,21,19,36,43,34,33,42,36,42,335
28,26,PUNJAB,104,112,240,321,355,329,442,457,383,462,435,449,"4,089"
29,27,RAJASTHAN,493,506,543,593,596,593,729,574,569,"1,301",717,643,"7,857"
30,28,SIKKIM,0,0,0,1,3,1,2,5,2,0,0,2,16
31,29,TAMIL NADU,593,579,810,857,817,870,"1,148","1,082","1,061","1,142","1,193","1,123","11,275"
32,30,TRIPURA,2,5,3,5,3,4,7,3,3,9,4,0,48
33,31,UT OF DNH AND DD,3,5,7,16,20,18,30,31,22,25,20,18,215
34,32,UTTARAKHAND,47,60,52,59,91,71,92,81,77,114,137,92,973
35,33,UTTAR PRADESH,467,450,590,730,782,817,"1,995","1,871","1,220","2,905","1,869","1,983","15,679"
36,34,WEST BENGAL,173,160,200,254,259,241,360,300,304,380,404,401,"3,436"

In [4]:
def preprocess_by_month(df, year):
    # Drop first two rows
    if 'JAN' in df.iloc[2].values:
        df = df.iloc[2:, 1:]
    else:
        df = df.iloc[3:, 1:]

    # Extract column names from the first remaining row
    cols = df.iloc[0].astype(str).str.strip().values
    cols[0] = 'STATE'
    cols[-1] = 'TOTAL'
    df.columns = cols

    # Drop the header row from data
    df = df.iloc[1:].reset_index(drop=True)

    # Add year column
    df['year'] = year

    # Clean category names
    # df['Fuel_Type'] = df['vehicle_category'].str.strip()
    # df['vehicle_category'] = df['vehicle_category'].map({
    #     'FOUR WHEELER (INVALID CARRIAGE)': '4WIC',
    #     'LIGHT MOTOR VEHICLE': 'LMV',
    #     'MEDIUM MOTOR VEHICLE': 'MMV',
    #     'HEAVY MOTOR VEHICLE': 'HMV'
    # })

    # Reorder columns: 'year' first
    priority = ['year']
    rest = [col for col in df.columns if col not in priority]
    # print(df.head())
    df = df.reindex(columns=priority + rest)

    # Filter valid categories
    # df = df[df['vehicle_category'].isin(['4WIC', 'LMV', 'MMV', 'HMV'])]

    return df

In [5]:
d = preprocess_by_month(data, 2024)
d

,year,STATE,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,TOTAL
0,2024,ANDAMAN & NICOBAR ISLAND,0,0,0,1,2,3,0,3,2,2,2,5,20
1,2024,ANDHRA PRADESH,126,129,399,437,540,638,724,219,202,244,692,676,"5,026"
2,2024,ARUNACHAL PRADESH,5,4,2,5,1,6,12,6,7,12,13,8,81
3,2024,ASSAM,20,24,64,41,42,46,69,70,68,58,76,96,674
4,2024,BIHAR,59,75,112,102,90,101,112,100,78,158,142,89,"1,218"
5,2024,CHANDIGARH,121,91,138,124,151,156,240,215,188,403,210,233,"2,270"
6,2024,CHHATTISGARH,135,144,204,171,171,169,233,351,120,402,194,178,"2,472"
7,2024,DELHI,567,503,733,800,839,"1,041","1,131",894,540,892,682,827,"9,449"
8,2024,GOA,85,100,117,144,112,91,133,132,105,164,117,122,"1,422"
9,2024,GUJARAT,493,510,770,758,762,627,"1,066",952,975,"1,668","1,032","1,198","10,811"
10,2024,HARYANA,236,169,209,451,453,541,629,711,818,"1,007","1,095","1,078","7,397"
11,2024,HIMACHAL PRADESH,15,11,18,43,51,47,63,64,60,75,99,72,618
12,2024,JAMMU AND KASHMIR,13,25,34,25,24,29,33,31,41,70,42,60,427
13,2024,JHARKHAND,24,32,47,52,60,61,79,76,98,104,88,71,792
14,2024,KARNATAKA,847,839,"1,330","1,195","1,260","1,249","1,311","1,798","1,335","2,412","1,913","1,708","17,197"
15,2024,KERALA,913,851,"1,032","1,235","1,154","1,040","1,199","1,189","1,484","1,537","1,472","1,425","14,531"
16,2024,LADAKH,0,0,0,0,0,0,0,2,0,0,0,0,2
17,2024,MADHYA PRADESH,204,192,226,225,221,271,314,307,235,603,364,295,"3,457"
18,2024,MAHARASHTRA,"1,131","1,051","1,377","1,731","1,747","1,506","2,027","1,946","1,884","3,626","2,212","2,407","22,645"
19,2024,MANIPUR,7,7,2,7,7,4,10,10,10,11,11,14,100
20,2024,MEGHALAYA,1,4,3,7,9,7,7,2,8,9,9,6,72
21,2024,MIZORAM,1,0,0,0,0,1,1,3,2,2,3,3,16
22,2024,NAGALAND,0,1,2,2,6,0,3,5,7,8,1,0,35
23,2024,ODISHA,144,201,217,202,239,167,299,237,205,420,344,367,"3,042"
24,2024,PUDUCHERRY,10,14,5,21,19,36,43,34,33,42,36,42,335
25,2024,PUNJAB,104,112,240,321,355,329,442,457,383,462,435,449,"4,089"
26,2024,RAJASTHAN,493,506,543,593,596,593,729,574,569,"1,301",717,643,"7,857"
27,2024,SIKKIM,0,0,0,1,3,1,2,5,2,0,0,2,16
28,2024,TAMIL NADU,593,579,810,857,817,870,"1,148","1,082","1,061","1,142","1,193","1,123","11,275"
29,2024,TRIPURA,2,5,3,5,3,4,7,3,3,9,4,0,48
30,2024,UT OF DNH AND DD,3,5,7,16,20,18,30,31,22,25,20,18,215
31,2024,UTTARAKHAND,47,60,52,59,91,71,92,81,77,114,137,92,973
32,2024,UTTAR PRADESH,467,450,590,730,782,817,"1,995","1,871","1,220","2,905","1,869","1,983","15,679"
33,2024,WEST BENGAL,173,160,200,254,259,241,360,300,304,380,404,401,"3,436"

In [6]:
data_by_months = pd.DataFrame()
for i in range(2002,2026):
    df = pd.read_excel(f'./data/State_ev_data/{i}.xlsx', header=None)
    print(i)
    pre_processed = preprocess_by_month(df, i)
    data_by_months = pd.concat((data_by_months, pre_processed), ignore_index=True)

d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

2002
2003
2004
2005
2006
2007

d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

2008
2009
2010
2011
2012

d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

2013
2014
2015
2016
2017

d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

2018
2019
2020
2021
2022
2023
2024
2025

d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
d:\Vahan parivahan\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [7]:
data_by_months

,year,STATE,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,TOTAL
0,2002,DELHI,0,0,1,0,3,3,2,2,0,0,0,1,12
1,2002,GOA,0,0,0,0,1,2,0,0,0,0,0,0,3
2,2002,GUJARAT,0,2,0,2,0,0,0,5,0,0,1,0,10
3,2002,HIMACHAL PRADESH,0,0,0,0,0,0,1,0,0,0,0,0,1
4,2002,JAMMU AND KASHMIR,0,0,0,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,2025,TRIPURA,4,4,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
532,2025,UT OF DNH AND DD,57,23,19,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122
533,2025,UTTARAKHAND,131,105,120,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,447
534,2025,UTTAR PRADESH,"2,461","1,818","1,849","1,137",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,265"
535,2025,WEST BENGAL,481,379,451,414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,725"

In [8]:
data_by_months.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    536 non-null    int64
 1   STATE   536 non-null    object
 2   JAN     536 non-null    object
 3   FEB     536 non-null    object
 4   MAR     536 non-null    object
 5   APR     536 non-null    object
 6   MAY     502 non-null    object
 7   JUN     502 non-null    object
 8   JUL     502 non-null    object
 9   AUG     502 non-null    object
 10  SEP     502 non-null    object
 11  OCT     502 non-null    object
 12  NOV     502 non-null    object
 13  DEC     502 non-null    object
 14  TOTAL   536 non-null    object
dtypes: int64(1), object(14)
memory usage: 62.9+ KB

In [9]:
cols = data_by_months.columns

In [11]:
for col in cols:
    if col != 'STATE':
        data_by_months[col] = data_by_months[col].map(
            lambda x: int(str(x).replace(',', '')) if pd.notna(x) else x
        )

In [12]:
data_by_months.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    536 non-null    int64
 1   STATE   536 non-null    object
 2   JAN     536 non-null    int64
 3   FEB     536 non-null    int64
 4   MAR     536 non-null    int64
 5   APR     536 non-null    int64
 6   MAY     502 non-null    float64
 7   JUN     502 non-null    float64
 8   JUL     502 non-null    float64
 9   AUG     502 non-null    float64
 10  SEP     502 non-null    float64
 11  OCT     502 non-null    float64
 12  NOV     502 non-null    float64
 13  DEC     502 non-null    float64
 14  TOTAL   536 non-null    int64
dtypes: float64(8), int64(6), object(1)
memory usage: 62.9+ KB

In [13]:
data_by_months.to_csv('./data/state_ev_by_months.csv', index=False)